export const TOOL_DESCRIPTIONS_EN: Record<string, string> = {
  browser_navigate: "Navigate to a URL. Input: full URL (e.g. https://example.com).",
  browser_wait_for_navigation: "Wait for navigation to complete. Input: load|domcontentloaded|networkidle|all (default: all).",
  browser_navigate_back: "Go back to the previous page (history.back()). No input.",
  browser_navigate_forward: "Go forward to the next page (history.forward()). No input.",
  browser_click: "Click an element. Input: CSS selector or visible text to click.",
  browser_type: "Type text into a field. Input: selector|text (e.g. input[name=\"q\"]|hello).",
  browser_handle_dialog: "Accept or dismiss a dialog. Input: accept|dismiss, optionally |text for prompt.",
  browser_keyboard_type: "Type text via keyboard on the active element. Input: text to type.",
  browser_press_key: "Press a key (e.g. Enter, Tab, Escape). Input: key name.",
  browser_move_mouse: "Move mouse to given coordinates. Input: x,y (e.g. 100,200).",
  browser_click_xy: "Click at given coordinates. Input: x,y (e.g. 100,200).",
  browser_drag: "Drag from one point to another. Input: x1,y1,x2,y2.",
  browser_get_title: "Return the current page title.",
  browser_snapshot_dom: "Capture HTML snapshot of the page. Options: selector=css, clean, structure, limit=N.",
  browser_query: "Return up to 10 HTML elements matching the given CSS selector.",
  browser_accessible_tree: "Return the AX accessibility tree (JSON). Input 'all' for full tree.",
  browser_read_text: "Return all visible text on the page in DOM order.",
  browser_screenshot: "Take a screenshot. Input: (empty) for viewport, 'full' for full page.",
  browser_get_active_tab: "Return info about the active tab (index, URL, title).",
  browser_navigate_tab: "Navigate a specific tab without switching. Input: tabIndex|url.",
  browser_screenshot_tab: "Screenshot a specific tab. Input: tabIndex[,full].",
  browser_tab_list: "List open tabs with their indexes and URLs.",
  browser_tab_new: "Open a new tab. Optional input: URL. Does not auto-switch to the new tab.",
  browser_tab_select: "Switch to the tab at the given index. Input: tab index.",
  browser_tab_close: "Close the tab at the given index. Input: tab index.",
  save_memory: "Save an automation pattern for a domain. Use after successful tool sequences.",
  lookup_memories: "Look up saved memories for a domain. Input: domain (e.g. www.google.com).",
  get_all_memories: "Return all saved memories across all domains.",
  delete_memory: "Delete a specific memory by ID.",
  clear_all_memories: "Delete all saved memories. Use with caution.",
  extract_with_schema: "Extract structured data from the page as JSON conforming to the given schema. Input: JSON {schema, hint?, useAccessibilityTree?}.",
  paginate_and_collect: "Collect data across multiple pages using extract_with_schema. Input: JSON {schema, nextButtonSelector?, nextButtonText?, maxPages?, deduplicateField?}.",
  fill_form_from_data: "Fill form fields from a structured data payload. Does NOT submit. Input: JSON {data: {field: value}, submitSelector?}.",
  play_automation: "Replay a recorded automation sequence step by step using browser tools. Input: JSON {recordingName, instruction?, confirmBeforeEachStep?}.",
  use_skill: "Execute a saved skill by title. Interprets steps (navigate, extract, paginate, fill, play) and returns the execution prompt. Input: JSON {skillTitle, params?}.",
};
