export const TOOL_DESCRIPTIONS_IT: Record<string, string> = {
  browser_navigate: "Naviga a un URL. Input: URL completo (es. https://esempio.com).",
  browser_wait_for_navigation: "Attendi il completamento della navigazione. Input: load|domcontentloaded|networkidle|all (default: all).",
  browser_navigate_back: "Torna alla pagina precedente (history.back()). Nessun input.",
  browser_navigate_forward: "Avanza alla pagina successiva (history.forward()). Nessun input.",
  browser_click: "Clicca su un elemento. Input: selettore CSS o testo visibile da cliccare.",
  browser_type: "Digita testo in un campo. Input: selettore|testo (es. input[name=\"q\"]|ciao).",
  browser_handle_dialog: "Accetta o scarta un dialog. Input: accept|dismiss, opzionale |testo per prompt.",
  browser_keyboard_type: "Digita testo via tastiera sull'elemento attivo. Input: testo da digitare.",
  browser_press_key: "Premi un tasto (es. Enter, Tab, Escape). Input: nome del tasto.",
  browser_move_mouse: "Sposta il mouse alle coordinate date. Input: x,y (es. 100,200).",
  browser_click_xy: "Clicca alle coordinate date. Input: x,y (es. 100,200).",
  browser_drag: "Trascina da un punto a un altro. Input: x1,y1,x2,y2.",
  browser_get_title: "Restituisce il titolo della pagina corrente.",
  browser_snapshot_dom: "Cattura snapshot HTML della pagina. Opzioni: selector=css, clean, structure, limit=N.",
  browser_query: "Restituisce fino a 10 elementi HTML che corrispondono al selettore CSS fornito.",
  browser_accessible_tree: "Restituisce l'albero di accessibilità AX (JSON). Input 'all' per albero completo.",
  browser_read_text: "Restituisce tutto il testo visibile della pagina in ordine DOM.",
  browser_screenshot: "Cattura uno screenshot. Input: (vuoto) per viewport, 'full' per pagina intera.",
  browser_get_active_tab: "Restituisce info sul tab attivo (indice, URL, titolo).",
  browser_navigate_tab: "Naviga un tab specifico senza cambiarlo. Input: indiceTab|url.",
  browser_screenshot_tab: "Screenshot di un tab specifico. Input: indiceTab[,full].",
  browser_tab_list: "Elenca i tab aperti con indici e URL.",
  browser_tab_new: "Apre un nuovo tab. Input opzionale: URL. Non cambia tab attivo automaticamente.",
  browser_tab_select: "Cambia al tab con l'indice dato. Input: indice tab.",
  browser_tab_close: "Chiude il tab con l'indice dato. Input: indice tab.",
  save_memory: "Salva un pattern di automazione per un dominio. Usare dopo sequenze di tool riuscite.",
  lookup_memories: "Cerca memorie salvate per un dominio. Input: dominio (es. www.google.com).",
  get_all_memories: "Restituisce tutte le memorie salvate su tutti i domini.",
  delete_memory: "Elimina una memoria specifica per ID.",
  clear_all_memories: "Cancella tutte le memorie salvate. Usare con cautela.",
  extract_with_schema: "Estrae dati strutturati dalla pagina come JSON conforme allo schema. Input: JSON {schema, hint?, useAccessibilityTree?}.",
  paginate_and_collect: "Raccoglie dati su più pagine con extract_with_schema. Input: JSON {schema, nextButtonSelector?, nextButtonText?, maxPages?, deduplicateField?}.",
  fill_form_from_data: "Compila i campi di un form da un payload strutturato. NON fa submit. Input: JSON {data: {campo: valore}, submitSelector?}.",
  play_automation: "Riproduce una sequenza registrata step by step usando i tool browser. Input: JSON {recordingName, instruction?, confirmBeforeEachStep?}.",
  use_skill: "Esegue una skill salvata per titolo. Interpreta i passi (navigate, extract, paginate, fill, play) e restituisce il prompt di esecuzione. Input: JSON {skillTitle, params?}.",
};
